config/routes.rb
Webplaylist::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  resources :playlists
  resources :songs

  root to: 'static_pages#welcome'

  

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
	belongs_to :user
	has_many :playlistations, dependent: :destroy
	has_many :songs, :through => :playlistations

	validates :title, presence: { message: 'Please provide a name' }

	accepts_nested_attributes_for :songs, :playlistations
end

app/models/playlistation.rb
class Playlistation  < ActiveRecord::Base
	belongs_to :playlist 
	belongs_to :song
end

app/models/song.rb
class Song < ActiveRecord::Base
	has_many :playlistations, dependent: :destroy
	has_many :playlists, :through => :playlistations

	validates :url, presence: { message: 'Please provide a url'}

	accepts_nested_attributes_for :playlists, :playlistations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :playlists

	def self.from_omniauth(auth)
		where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
			user.provider = auth.provider
		    user.uid = auth.uid
		    user.name = auth.info.name
		    user.oauth_token = auth.credentials.token
		    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
		    user.save!
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
	  def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end
	  helper_method :current_user
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
	def index
		if current_user
			@playlists = current_user.playlists
			@playlist = @playlists.first
			@songs = @playlist.songs
		else
			redirect_to root_url
		end
	end

	def new

	end

	def create
		@playlist = Playlist.new(title:params[:title], user_id:params[:user_id])
		if @playlist.save
			respond_to do |format|
				format.html {redirect_to :back}
    			format.js
    		end
		end
	end

	def show
		@playlist = current_user.playlists.find(params[:id])
		@songs = @playlist.songs
		respond_to do |format|
		  format.html
	      format.js
   		end
	end

	def update
		@playlist = Playlist.find(params[:id])
	end

	private
		def post_params
			params.require(:playlist).permit(:title, :user_id)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		user = User.from_omniauth(env['omniauth.auth'])
		session[:user_id] = user.id
		redirect_to playlists_path
	end

	def destroy
    	session[:user_id] = nil
    	redirect_to root_url
  	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	include SongsHelper

	def new

	end

	def create
		@playlist = Playlist.all.find_by_id(params[:pl_id])
		puts "hereyougo #{params[:pl_id]}"
		puts params[:url]
		songid = getID(params[:url])
		@song = Song.new(url:params[:url], youtubeid: songid)
		puts @song
		@song.save
		@playlistation = Playlistation.new(song_id:@song.id,playlist_id:@playlist.id)
		if @playlistation.save
			respond_to do |format|
				format.html {redirect_to :back}
    			format.js
    		end
		end
	end

	private
		def playlist_params
			params.require(:playlist).permit(:id)
		end

		def song_params
			params.require(:songs).permit(:url)
		end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  	if current_user
  		redirect_to playlists_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
	def getID(youtube_url)
		regex = /^(?:http:\/\/)?(?:www\.)?\w*\.\w*\/(?:watch\?v=)?((?:p\/)?[\w\-]+)/
   		youtube_url.match(regex)[1]
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Webplaylist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="user_nav">
  <% if current_user %>
    Signed in as <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
  <% else %>
    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
  <% end %>
</div>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/playlists/_playlist.html.erb
<%= link_to(playlist_path(playlist), {class: "playlist_part playlist-#{playlist.id} do_this_playlist",remote: true}) do %>
	<% if defined? indexused %>
		<% if playlist_counter == (indexused-1) %>
		   <li class="pl_selected">
		<% else %>
			<li>
		<% end %>
	<% else %>
	  	<li>
	<% end %>
	  <span class="content"><%= playlist.title %></span>
	<!--  <span class="timestamp">
	    Posted <%= time_ago_in_words(playlist.created_at) %> ago.
	  </span> -->
	</li>
<% end %>

app/views/playlists/create.js.erb
<% if @playlist.valid? %>

$('.playlists').append('<%= escape_javascript(render @playlist) %>')
$('.playlists title').val('')

<% end %>

app/views/playlists/index.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <% if @playlists %>
          <ul class="playlists">
            <%= render @playlists, :indexused => @playlist.id %>
          </ul>
      <% end %>
      <%= form_tag('/playlists', method: :post, remote: true) do %>
        <%= text_field_tag(:title, nil, {placeholder: 'New playlist', autocomplete: "off"}) %>
        <%= hidden_field_tag(:user_id, @current_user.id) %>
      <% end %> 
    </section>
  </aside>
    <div class="span8" id="songspan">
      <div id="player">
      </div>


    <% if @playlist.songs %>
      <h3>Songs</h3>
        <ul class="songs">
        <li> 
        </li>
        <div id="songs_form_to_render">
          <%= render @songs %>
        </div>
        <li> 
          <%= form_tag('/songs', method: :post, remote: true) do %>
          <%= text_field_tag(:url, nil,{placeholder: 'Add song', id: "song_url", autocomplete: "off"}) %>
          <%= hidden_field_tag(:pl_id, @playlist.id) %>
          <% end %> 
        </li>
      </ul>
    <% end %>

  </div>
</div>

app/views/playlists/new.html.erb
<%= form_for :playlist, url: playlists_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/playlists/show.js.erb
$('#songs_form_to_render').html('<%= j render @songs %>');

$('#pl_id').val('<%= @playlist.id %>');

bindsongs($('#songs_form_to_render'));

app/views/songs/_song.html.erb
 <%= content_tag :div, class: "song_part song-#{song.id}", data: { songs: @songs, index: song_counter } do %>
	<li class: "song_item">
	 <%= puts song.url %>
	  <span class="content"><%= song.url %></span>
	<!--  <span class="timestamp">
	    Posted <%= time_ago_in_words(song.created_at) %> ago.
	  </span> -->
	</li>
<% end %>

app/views/songs/create.js.erb
$('#songs_form_to_render').append('<%= escape_javascript(render @song, :song_counter => (@playlist.songs.count + 1)) %>')
$('#song_url').val('')

app/views/songs/new.html.erb
<h1>song added!</h1>

app/views/static_pages/welcome.html.erb
<html>
	<head>
		<title>Welcome to Webplaylist</title>
	</head>
	<body class="welcomepage">
		<label id="intro">Webplaylist</label>
		<label id="introsub">Make playlists from Youtube!</label>
		<button id="sign_in", "btn btn-danger btn-large">
	</body>
</html>